In [1]:
import pandas as pd

In [2]:
data = pd.read_csv(
    "../data/data.csv.gz",
    compression="gzip",
    sep="\t",         
    header=None,
    names = ["letter", "value", "date","codes", "metrics"]
).sort_values("letter")

data

   letter  value        date    codes                               metrics
28      A      6  1999-07-29      f,e        hhh:6,jjj:13,eee:5,iii:7,ccc:3
1       A      2  1999-10-28    a,f,c               ccc:2,ddd:0,aaa:3,hhh:9
30      A      9  1998-04-26      b,f         ccc:6,aaa:9,eee:5,ddd:0,bbb:3
3       A      3  1999-08-28      a,b               hhh:9,iii:5,eee:7,bbb:1
23      A      9  1999-08-25    f,a,d        jjj:12,ggg:7,ccc:7,ddd:9,bbb:3
5       A      7  1998-07-28      c,d         bbb:2,hhh:0,ccc:4,fff:1,aaa:7
6       A      9  1997-02-28    g,d,a   aaa:5,fff:8,ddd:2,iii:0,jjj:7,ccc:1
26      A      8  1997-09-28    a,e,f                     fff:0,ddd:5,ccc:4
33      B      4  1998-03-23    b,f,c   iii:7,ggg:3,ddd:0,jjj:8,hhh:5,ccc:1
34      B      6  1999-04-21    f,a,e         hhh:6,ccc:3,jjj:9,bbb:8,ddd:7
14      B      9  1999-08-12      d,b         ccc:7,jjj:6,fff:7,ddd:3,aaa:2
36      B      8  1997-05-21      c,a       ddd:5,jjj:17,iii:7,ccc:10,bbb:4
9       B      3  1999-11-23  d,b,g,f   bbb:7,jjj:9,fff:5,iii:4,ggg:3,eee:3
7       B      1  1999-05-10      b,a                     fff:3,hhh:1,ddd:2
2       B      5  1998-05-02  f,e,a,c              ddd:2,ggg:5,ccc:6,jjj:12
10      C      7  1998-01-17  d,c,f,b        hhh:6,eee:4,iii:0,fff:2,jjj:12
37      C      9  1997-07-22  c,a,e,f                     eee:3,fff:2,hhh:6
4       C      6  1999-12-01  f,g,d,a              iii:6,ddd:5,eee:4,jjj:12
29      C      0  1999-08-22  f,c,a,g  eee:1,fff:4,aaa:2,ccc:7,ggg:10,ddd:6
11      C      5  1998-12-28  d,e,a,c                     bbb:7,iii:6,ggg:9
12      D      3  1999-10-15  g,e,f,b         bbb:9,aaa:3,ccc:6,fff:4,eee:2
15      D      8  1997-12-01      f,e               ccc:8,eee:6,bbb:9,ddd:3
35      D      7  1999-02-29      a,f                     aaa:1,fff:5,ddd:3
17      D      5  1998-08-12      g,a                     hhh:4,jjj:5,ccc:9
31      D      3  1998-02-24      b,f   bbb:7,hhh:1,aaa:6,iii:4,fff:9,ddd:5
22      D      5  1999-06-25    c,f,a                    eee:3,jjj:17,ddd:7
32      E      5  1999-03-24      a,c               fff:3,ccc:1,ggg:3,eee:5
0       E      1  1999-02-28    b,g,f        jjj:12,bbb:3,ddd:9,ggg:8,hhh:2
19      E      9  1998-01-23      e,a                     bbb:9,aaa:3,fff:1
25      E      6  1997-09-24    e,d,c   fff:3,eee:6,iii:4,bbb:7,ddd:4,ccc:1
24      E      4  1997-07-26      c,d   jjj:6,ccc:4,aaa:1,hhh:9,iii:7,ggg:8
21      E      3  1999-04-24    c,b,g                     ccc:5,fff:8,iii:7
20      E      7  1999-06-22      e,f                     ddd:9,iii:2,aaa:4
38      E      1  1999-09-28      e,d                     fff:9,iii:2,eee:5
18      E      8  1999-08-24  e,c,f,a                     ccc:1,iii:6,fff:9
16      E      3  1997-07-28    e,b,f   bbb:6,iii:3,hhh:5,fff:4,ggg:9,ddd:2
13      E      8  1998-11-01      c,f                    aaa:8,ddd:5,jjj:12
8       E      2  1997-04-12  d,e,a,f   eee:4,ccc:5,iii:9,fff:7,ggg:6,bbb:2
27      E      5  1999-06-22    c,a,g        ggg:6,hhh:3,ddd:9,ccc:10,jjj:7
39      E      5  1998-01-26    f,a,d                     hhh:8,ggg:3,jjj:5

In [3]:
#Pregunta 3

x = data.groupby(["letter"])["letter"].count().to_dict()
list = []
for key, value in x.items():
    list.append((key, value))

print(list)

[('A', 8), ('B', 7), ('C', 5), ('D', 6), ('E', 14)]

In [4]:
#Pregunta 4

data["month"] = pd.to_datetime(data["date"], errors="coerce").dt.strftime("%m")

In [5]:
#Pregunta 5

dict = data.groupby(["letter"])["value"].agg(["min", "max"]).to_dict()

dict_min_max = []
for letra in data["letter"].unique():
    max = dict["max"][letra]
    min = dict["min"][letra]
    dict_min_max.append((letra, max, min))

In [7]:
#Pregunta 6

data_melt = data["metrics"].str.split(",", expand=True).melt().dropna()
data_melt = data_melt["value"].str.split(":", expand=True)
data_melt.columns = ["clave", "value"]

dict = data_melt.groupby(["clave"])["value"].agg(["min", "max"]).to_dict()

dict_min_max = []
for clave in dict["min"].keys():
    max = dict["min"][clave]
    min = dict["max"][clave]
    dict_min_max.append((clave, min, max))

In [34]:
#Pregunta 7
count = data.groupby("value")["letter"].agg(lambda x: [v for v in x])
lista_tuplas = [(idx, val) for idx, val in zip(count.index, count.values)]
print(lista_tuplas)

[(0, ['C']), (1, ['B', 'E', 'E']), (2, ['A', 'E']), (3, ['A', 'B', 'D', 'D', 'E', 'E']), (4, ['B', 'E']), (5, ['B', 'C', 'D', 'D', 'E', 'E', 'E']), (6, ['A', 'B', 'C', 'E']), (7, ['A', 'C', 'D', 'E']), (8, ['A', 'B', 'D', 'E', 'E']), (9, ['A', 'A', 'A', 'B', 'C', 'E'])]

In [35]:
#Pregunta 8
count = data.groupby("value")["letter"].agg(lambda x: [v for v in x.unique()])
lista_tuplas = [(idx, val) for idx, val in zip(count.index, count.values)]
print(lista_tuplas)

[(0, ['C']), (1, ['B', 'E']), (2, ['A', 'E']), (3, ['A', 'B', 'D', 'E']), (4, ['B', 'E']), (5, ['B', 'C', 'D', 'E']), (6, ['A', 'B', 'C', 'E']), (7, ['A', 'C', 'D', 'E']), (8, ['A', 'B', 'D', 'E']), (9, ['A', 'B', 'C', 'E'])]

In [ ]:
#Pregunta 9

data_melt = data["metrics"].str.split(",", expand=True).melt().dropna()
data_melt = data_melt["value"].str.split(":", expand=True)
data_melt.columns = ["clave", "value"]

data_melt = data_melt.drop(["value"], axis=1).sort_values("clave")
conteo = data_melt["clave"].value_counts(sort = False).to_dict()
print(conteo)

In [72]:
#Pregunta 10
data = pd.read_csv(
    "../data/data.csv.gz",
    compression="gzip",
    sep="\t",         
    header=None,
    names = ["letter", "value", "date","codes", "metrics"]
)

data["count_metrics"] = data["metrics"].str.split(",").apply(len)
data["count_codes"] = data["codes"].str.split(",").apply(len)

tuplas = []
for _,row in data.iterrows():
    tuplas.append((row["letter"], row["count_codes"], row["count_metrics"]))

print(tuplas)

[('E', 3, 5), ('A', 3, 4), ('B', 4, 4), ('A', 2, 4), ('C', 4, 4), ('A', 2, 5), ('A', 3, 6), ('B', 2, 3), ('E', 4, 6), ('B', 4, 6), ('C', 4, 5), ('C', 4, 3), ('D', 4, 5), ('E', 2, 3), ('B', 2, 5), ('D', 2, 4), ('E', 3, 6), ('D', 2, 3), ('E', 4, 3), ('E', 2, 3), ('E', 2, 3), ('E', 3, 3), ('D', 3, 3), ('A', 3, 5), ('E', 2, 6), ('E', 3, 6), ('A', 3, 3), ('E', 3, 5), ('A', 2, 5), ('C', 4, 6), ('A', 2, 5), ('D', 2, 6), ('E', 2, 4), ('B', 3, 6), ('B', 3, 5), ('D', 2, 3), ('B', 2, 5), ('C', 4, 3), ('E', 2, 3), ('E', 3, 3)]

In [ ]:
#Pregunta 12

data["metrics_list"] = data["metrics"].str.split(",")
df_exploded = data.explode("metrics_list")
df_exploded[["metric", "metric_value"]] = df_exploded["metrics_list"].str.split(":", expand=True)
df_exploded["metric_value"] = df_exploded["metric_value"].astype(int)
df_exploded.groupby("letter")["metric_value"].agg("sum").to_dict()

In [8]:
df_exploded.groupby("letter")["metric_value"].agg("sum").to_dict()

{'A': 177, 'B': 187, 'C': 114, 'D': 136, 'E': 324}

In [88]:
data_melt

    clave value
0     jjj    12
1     ccc     2
2     ddd     2
3     hhh     9
4     iii     6
..    ...   ...
224   ggg     8
225   ccc     1
229   ddd     6
231   ddd     5
233   ccc     1

[175 rows x 2 columns]